services:

  db-tasks:
    container_name: db-tasks
    image: mariadb:11
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: taskDB


volumes:
  data: